### ISSUE TITLE
Handle Camera and Microphone Selection

### ISSUE THREAD

**Issue by DamonOehlman** [rtc-io/rtc-captureconfig#1]
Using the `MediaStreamTrack.getSources` call we are able to find all the media devices available on the machine, which in turn gives us the ability to select a particular device for a particular call.

Need to modify the `camera:0` input to result in intelligence which means that camera selection will occur.

**Comment by silviapfeiffer** [comment]
we currently provide a custom array of available devices on which selection can occur. Any intelligence about which ones to prefer is left to the application, which is probably the right approach.
