### ISSUE TITLE
Provide option for generation of mandatory constraints

### ISSUE THREAD

**Issue by warrenjmcdonald** [rtc-io/rtc-captureconfig#5]
In certain cases mandatory capture constraints will be required. 

At present rtc-captureconfig returns an object with optional constraints. This was done to prevent capture failures if resolution spec could not be met by the device.

If an option could be provided to specify which form of constraint object is to be generated, then this can be used as appropriate for the application and.or device.

**Comment by DamonOehlman** [comment]
So something like:

```js
.toConstraints({ useMandatory: true });
```

??

**Comment by warrenjmcdonald** [comment]
That would work, with false or no option, keeping the current default
behaviour to generate optional

Cheers,


Warren





On 21 May 2015 at 09:51, Damon Oehlman <notifications@github.com> wrote:

> So something like:
>
> .toConstraints({ useMandatory: true });
>
> ??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtc-io/rtc-captureconfig/issues/5#issuecomment-104074158>
> .
>



-- 

Warren McDonald

**Comment by nathanoehlman** [comment]
Implemented in #6
