### ISSUE TITLE
height: and width: constraints generated are not compatible in some environments

### ISSUE THREAD

**Issue by warrenjmcdonald** [rtc-io/rtc-captureconfig#7]
The iOS native wrapper and the Temasys plugin both throw fatal exceptions when encountering the additional 
width:
 and 
height:
parameters in the generated constraints object.

**Comment by warrenjmcdonald** [comment]
Can I please bump this one as this is impacting operation in several test environments

**Comment by nathanoehlman** [comment]
Hi @warrenjmcdonald, I'll take a look at this today. Cheers!

**Comment by nathanoehlman** [comment]
Hi @warrenjmcdonald - if I could ask for a bit of extra information to help with replicating this issue, as I don't seem to be able to replicate the issue at the moment, at least with the Temasys plugin

1. Could you please provide a few known failing test cases (constraints along with the browser and version)
2. Also, if you could please indicate the version of the Temasys plugin that you are using (the latest is 0.8.854)

Cheers

**Comment by warrenjmcdonald** [comment]
Hi @nathanoehlman, sorry for delay.

Jeff Wang has a good example where the native iOS libs reject these generated height, width and framerate params. He had to filter them out in the iOS wrapper. 

See extract from testing below 

Constraints generated by capture config:
{
audio: true
video: {
	mandatory: {},
	optional: [
	{minFrameRate: 15}.
	{maxFrameRate: 15},
	{frameRate: 15}
	]
	}
}

Crash log from iOS:

May 25 10:14:37 Video-iPad MobileMail[361] <Notice>: 0x17806f180|EAS|Note |EAS Protocol Manager set to ASProtocol14_1
May 25 10:14:38 Video-iPad CoviuIOSTemplate[362] <Warning>: ### Javascript Log:iOS plugin initialized, getUserMedia available = true
May 25 10:14:38 Video-iPad CoviuIOSTemplate[362] <Error>: -[__NSArrayM objectForKey:]: unrecognized selector sent to instance 0x167b7b70
May 25 10:14:38 Video-iPad CoviuIOSTemplate[362] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM objectForKey:]: unrecognized selector sent to instance 0x167b7b70'

**Comment by nathanoehlman** [comment]
Thanks for that @warrenjmcdonald - I'll look into it some more.

**Comment by silviapfeiffer** [comment]
http://w3c.github.io/mediacapture-main/#media-track-supported-constraints is what the spec says should be supported, but apparently isn't implemented everywhere yet.

**Comment by warrenjmcdonald** [comment]
The implementations differ in what a video media capture constraint object can contain. It is very clear what parameters should be able to be set. It is not so obvious what the valid forms of the constraints can be for each implememtation. Min + max boundaries and/or specific values.

**Comment by nathanoehlman** [comment]
Hi @warrenjmcdonald - I've just pushed out `rtc-captureconfig` `3.0.0` which should fix this issue - at least it does for the Temasys plugin (I don't currently have access to an iOS device, so I'm not sure about that - although it should).

If you could test the new version to make sure that it works for your build, and let me know if you have any issues, that'd be great.

More details about the changes can be found in PR #8 and in the updated readme. 

Cheers,
Nathan
